let entries=[],activeSection="ALL";
const q=document.getElementById("query"),tabs=document.getElementById("sectionTabs"),eventList=document.getElementById("eventList"),eventSummary=document.getElementById("eventSummary"),searchBox=document.getElementById("searchBox"),searchResults=document.getElementById("searchResults"),searchTitle=document.getElementById("searchTitle"),searchCount=document.getElementById("searchCount"),infoModal=document.getElementById("infoModal"),infoContent=document.getElementById("infoContent"),playerModal=document.getElementById("playerModal"),playerContent=document.getElementById("playerContent");
const esc=v=>String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const norm=v=>String(v??"").toLowerCase().replace(/\s+/g," ").trim();
const sort=(a,b)=>String(a).localeCompare(String(b),undefined,{numeric:true,sensitivity:"base"});
function uniquePlayers(items){const m=new Map();items.forEach(x=>{const k=x.backNo+"||"+x.competitor;if(!m.has(k))m.set(k,{backNo:x.backNo,competitor:x.competitor,entryType:x.entryType})});return[...m.values()].sort((a,b)=>sort(a.backNo,b.backNo)||sort(a.competitor,b.competitor))}
function groupEvents(items){const m=new Map();items.forEach(x=>{const k=x.event+"||"+x.section+"||"+x.style;if(!m.has(k))m.set(k,{event:x.event,section:x.section,style:x.style,division:x.division,items:[]});m.get(k).items.push(x)});let arr=[...m.values()];arr.sort((a,b)=>{const aLast=/amateur couple latin/i.test(a.event)?1:0,bLast=/amateur couple latin/i.test(b.event)?1:0;if(aLast!==bLast)return aLast-bLast;return sort(a.section,b.section)||sort(a.event,b.event)});return arr}
function renderTabs(){const sections=["ALL",...new Set(entries.map(x=>x.section).filter(Boolean))];tabs.innerHTML=sections.map(s=>`<button class="section-tab ${s===activeSection?"active":""}" data-section="${esc(s)}">${esc(s)}</button>`).join("");tabs.querySelectorAll("button").forEach(b=>b.onclick=()=>{activeSection=b.dataset.section;renderTabs();renderEvents()})}
function renderEvents(){const filtered=activeSection==="ALL"?entries:entries.filter(x=>x.section===activeSection);const events=groupEvents(filtered);eventSummary.textContent=`${events.length} SECTIONS`;eventList.innerHTML=events.map(e=>{const ps=uniquePlayers(e.items);return`<article class="event-card"><div class="event-head"><span><span class="event-name">${esc(e.event)}</span><span class="event-meta">${esc(e.section)} · ${esc(e.style)}</span></span><span class="entry-count">${ps.length} ENTRIES</span></div><table class="participant-table"><thead><tr><th>BACK NO.</th><th>COMPETITOR / TEAM</th><th>TYPE</th></tr></thead><tbody>${ps.map(p=>`<tr><td>${esc(p.backNo)}</td><td><button class="participant-name-btn" data-back="${esc(p.backNo)}" data-name="${esc(p.competitor)}">${esc(p.competitor)}</button></td><td>${esc(p.entryType||"")}</td></tr>`).join("")}</tbody></table></article>`}).join("");eventList.querySelectorAll(".participant-name-btn").forEach(b=>b.onclick=()=>openPlayer(b.dataset.back,b.dataset.name))}
function openPlayer(back,name){const items=entries.filter(x=>x.backNo===back&&x.competitor===name).sort((a,b)=>sort(a.section,b.section)||sort(a.event,b.event));playerContent.innerHTML=`<div class="player-head"><div class="player-back">BACK NO. ${esc(back)}</div><h3>${esc(name)}</h3></div>${items.map(x=>`<div class="player-event"><div class="player-event-title">${esc(x.event)}</div><div class="player-event-meta">${esc(x.section)} · ${esc(x.style)} · ${esc(x.division)}</div></div>`).join("")}`;playerModal.classList.remove("hidden")}
function doSearch(){const s=norm(q.value);if(!s){searchBox.classList.add("hidden");return}const matched=entries.filter(x=>norm([x.backNo,x.competitor,x.event,x.section,x.style,x.division].join(" ")).includes(s));const ps=uniquePlayers(matched);searchTitle.textContent=`SEARCH RESULTS: ${q.value.trim()}`;searchCount.textContent=`${ps.length} FOUND`;searchBox.classList.remove("hidden");searchResults.innerHTML=ps.length?ps.map(p=>{const n=entries.filter(x=>x.backNo===p.backNo&&x.competitor===p.competitor).length;return`<div class="result-card"><button data-back="${esc(p.backNo)}" data-name="${esc(p.competitor)}"><span class="result-back">${esc(p.backNo)}</span><span><span class="result-name">${esc(p.competitor)}</span><span class="result-sub">${n} SECTIONS</span></span><span>›</span></button></div>`}).join(""):`<div class="empty">NO RESULTS FOUND.</div>`;searchResults.querySelectorAll("button").forEach(b=>b.onclick=()=>openPlayer(b.dataset.back,b.dataset.name))}
function showInfo(type){if(type==="information"){infoContent.innerHTML=`<h2 class="info-title">INFORMATION</h2><div class="info-grid"><div><span>DATE</span><strong>2026.08.08 (SAT)</strong></div><div><span>VENUE</span><strong>Seocho Sports Complex</strong></div><div><span>HOSTED BY</span><strong>Dancefill Academy</strong></div><div><span>ORGANIZER</span><strong>Tei Kim</strong></div><div><span>SANCTIONED BY</span><strong>KDC (Korea Professional Dance Council)</strong></div></div>`}else{infoContent.innerHTML=`<h2 class="info-title">VENUE & DIRECTIONS</h2><div class="direction-box"><h3>SEOCHO SPORTS COMPLEX</h3><p><strong>Address</strong><br>73-48, Yangjae-daero 12-gil, Seocho-gu, Seoul</p><p><strong>Public Transportation</strong><br>From Yangjae Station Exit 10, take Seocho Village Bus No. 08 and get off at Seocho Sports Complex.</p><div class="map-links"><a href="https://map.naver.com/p/search/%EC%84%9C%EC%B4%88%EC%A2%85%ED%95%A9%EC%B2%B4%EC%9C%A1%EA%B4%80" target="_blank">NAVER MAP</a><a href="https://map.kakao.com/?q=%EC%84%9C%EC%B4%88%EC%A2%85%ED%95%A9%EC%B2%B4%EC%9C%A1%EA%B4%80" target="_blank">KAKAO MAP</a></div></div>`}infoModal.classList.remove("hidden")}
document.getElementById("searchForm").onsubmit=e=>{e.preventDefault();doSearch();q.blur()};

function goHome(){
  q.value="";
  activeSection="ALL";
  searchBox.classList.add("hidden");
  searchResults.innerHTML="";
  searchCount.textContent="";
  infoModal.classList.add("hidden");
  playerModal.classList.add("hidden");
  renderTabs();
  renderEvents();
  window.scrollTo({top:0,behavior:"smooth"});
}
document.getElementById("homeBtn").onclick=goHome;

document.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>showInfo(b.dataset.view));
document.querySelectorAll("[data-close-info]").forEach(b=>b.onclick=()=>infoModal.classList.add("hidden"));
document.querySelectorAll("[data-close-player]").forEach(b=>b.onclick=()=>playerModal.classList.add("hidden"));

fetch("players.json",{cache:"no-store"}).then(r=>r.json()).then(d=>{entries=d;renderTabs();renderEvents()}).catch(()=>eventList.innerHTML='<div class="empty">FAILED TO LOAD PLAYERS.JSON</div>');
