let entries=[],activeSection="전체";
const q=document.getElementById("query"),tabs=document.getElementById("sectionTabs"),list=document.getElementById("eventList"),summary=document.getElementById("eventSummary"),box=document.getElementById("searchBox"),results=document.getElementById("searchResults"),title=document.getElementById("searchTitle"),count=document.getElementById("searchCount"),modal=document.getElementById("playerModal"),modalBody=document.getElementById("modalBody");
const esc=v=>String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const norm=v=>String(v??"").toLowerCase().replace(/\s+/g," ").trim();
const sort=(a,b)=>String(a).localeCompare(String(b),undefined,{numeric:true,sensitivity:"base"});
function uniquePlayers(items){const m=new Map();items.forEach(x=>{const k=x.backNo+"||"+x.competitor;if(!m.has(k))m.set(k,{backNo:x.backNo,competitor:x.competitor})});return[...m.values()].sort((a,b)=>sort(a.backNo,b.backNo)||sort(a.competitor,b.competitor))}
function groupEvents(items){const m=new Map();items.forEach(x=>{const k=x.eventNo+"||"+x.event;if(!m.has(k))m.set(k,{eventNo:x.eventNo,event:x.event,section:x.section,style:x.style,items:[]});m.get(k).items.push(x)});return[...m.values()].sort((a,b)=>sort(a.eventNo,b.eventNo))}
function renderTabs(){const sections=["전체",...new Set(entries.map(x=>x.section).filter(Boolean))];tabs.innerHTML=sections.map(s=>`<button class="tab ${s===activeSection?"active":""}" data-s="${esc(s)}">${esc(s)}</button>`).join("");tabs.querySelectorAll("button").forEach(b=>b.onclick=()=>{activeSection=b.dataset.s;renderTabs();renderEvents()})}
function renderEvents(){const filtered=activeSection==="전체"?entries:entries.filter(x=>x.section===activeSection);const events=groupEvents(filtered);summary.textContent=events.length+"개 이벤트";list.innerHTML=events.map(e=>{const ps=uniquePlayers(e.items);return`<article class="event-card"><button class="event-toggle"><span class="event-no">EVENT ${esc(e.eventNo)}</span><span><span class="event-name">${esc(e.event)}</span><span class="event-meta">${esc(e.section)} · ${esc(e.style)}</span></span><span class="entry-count">${ps.length}명 ⌄</span></button><div class="participants">${ps.map(p=>`<button class="person-row" data-b="${esc(p.backNo)}" data-n="${esc(p.competitor)}"><span class="person-back">${esc(p.backNo)}</span><span class="person-name">${esc(p.competitor)}</span><span class="arrow">›</span></button>`).join("")}</div></article>`}).join("");list.querySelectorAll(".event-toggle").forEach(b=>b.onclick=()=>b.closest(".event-card").classList.toggle("open"));list.querySelectorAll(".person-row").forEach(b=>b.onclick=()=>openPlayer(b.dataset.b,b.dataset.n))}
function openPlayer(back,name){const items=entries.filter(x=>x.backNo===back&&x.competitor===name).sort((a,b)=>sort(a.eventNo,b.eventNo));modalBody.innerHTML=`<div class="player-head"><div class="player-back">BACK NO. ${esc(back)}</div><h3>${esc(name)}</h3></div>${items.map(x=>`<div class="player-event"><div class="player-event-title">EVENT ${esc(x.eventNo)} · ${esc(x.event)}</div><div class="player-event-meta">${esc(x.section)} · ${esc(x.style)} · ${esc(x.division)}</div></div>`).join("")}`;modal.classList.remove("hidden");document.body.style.overflow="hidden"}
function closeModal(){modal.classList.add("hidden");document.body.style.overflow=""}
function search(){const s=norm(q.value);if(!s){box.classList.add("hidden");return}const matched=entries.filter(x=>norm([x.backNo,x.competitor,x.eventNo,x.event,x.section,x.style,x.division].join(" ")).includes(s));const ps=uniquePlayers(matched);title.textContent=`"${q.value.trim()}" 검색 결과`;count.textContent=ps.length+"명";box.classList.remove("hidden");results.innerHTML=ps.length?ps.map(p=>{const n=entries.filter(x=>x.backNo===p.backNo&&x.competitor===p.competitor).length;return`<div class="result-card"><button data-b="${esc(p.backNo)}" data-n="${esc(p.competitor)}"><span class="result-back">${esc(p.backNo)}</span><span><span class="result-name">${esc(p.competitor)}</span><span class="result-sub">${n}개 참가 이벤트</span></span><span class="arrow">›</span></button></div>`}).join(""):`<div class="empty">검색 결과가 없습니다.</div>`;results.querySelectorAll("button").forEach(b=>b.onclick=()=>openPlayer(b.dataset.b,b.dataset.n))}
document.getElementById("searchForm").onsubmit=e=>{e.preventDefault();search();q.blur()};
document.getElementById("resetBtn").onclick=()=>{q.value="";box.classList.add("hidden");activeSection="전체";renderTabs();renderEvents()};
document.getElementById("closeModal").onclick=closeModal;document.querySelector("[data-close]").onclick=closeModal;
fetch("players.json",{cache:"no-store"}).then(r=>r.json()).then(d=>{entries=d;renderTabs();renderEvents()}).catch(()=>list.innerHTML='<div class="empty">players.json을 불러오지 못했습니다.</div>');
